"""
07_predict.py - Inference & Integration Pipeline for Amazon ML Challenge.

Responsibilities (Owned by Team Lead / Integration):
Integrates the upstream components from:
- Teammate 2: Candidate pairs from 03_blocking.py
- Teammate 3: Feature engineering from 04_features.py & trained model from 05_train.py

Pipeline Flow:
1. Load candidate pairs (s1_entity_id, candidate_entity_id, candidate_source).
2. Load trained classifier model (--model).
3. Compute/load pairwise features.
4. Score candidate pairs with match probabilities.
5. Apply configurable decision threshold (--threshold, default=0.80).
6. Aggregate matches per Source 1 entity and save to TSV.
"""

import argparse
import os
import sys
from collections import defaultdict
from typing import Dict, List, Optional, Set


def load_candidates(candidates_path: str):
    """
    Load candidate pairs generated by Teammate 2 (03_blocking.py).

    Expected format:
    s1_entity_id\tcandidate_entity_id\tcandidate_source
    """
    if not os.path.isfile(candidates_path):
        raise FileNotFoundError(f"Candidate pairs file not found: {candidates_path}")

    print(f"Loading candidate pairs from: {candidates_path}")
    # Integration hook: Teammate 2's output loader
    # In production, can return pandas DataFrame or streaming generator
    return candidates_path


def load_trained_model(model_path: str):
    """
    Load trained model artifact produced by Teammate 3 (05_train.py).
    """
    if not os.path.isfile(model_path):
        raise FileNotFoundError(f"Model file not found: {model_path}")

    print(f"Loading trained model from: {model_path}")
    try:
        import joblib
        model = joblib.load(model_path)
        return model
    except Exception as e:
        print(f"Error loading model with joblib: {e}")
        raise


def extract_features(candidates, feature_config: Optional[dict] = None):
    """
    Feature extraction interface hook connected to Teammate 3 (04_features.py).
    """
    print("Extracting/loading pairwise similarity features (owned by Teammate 3)...")
    # Placeholder for Teammate 3's feature extraction call
    return None


def predict_match_probabilities(model, features):
    """
    Run model inference to compute P(match=1) for each candidate pair.
    """
    print("Scoring candidate pairs with trained model...")
    # Placeholder: probabilities = model.predict_proba(features)[:, 1]
    return []


def group_predictions(
    scored_pairs: List[tuple],
    threshold: float = 0.80,
    reference_s1_ids: Optional[Set[str]] = None,
) -> Dict[str, List[str]]:
    """
    Filter candidate pairs by probability >= threshold and group by Source 1 ID.

    Args:
        scored_pairs: List of (s1_id, candidate_id, probability)
        threshold: Decision threshold for matching
        reference_s1_ids: Optional set of all Source 1 entities (to ensure singletons appear)

    Returns:
        Dict mapping source1_entity_id -> list of matched_entity_ids
    """
    grouped = defaultdict(list)

    # Initialize all reference S1 entities with empty lists if provided
    if reference_s1_ids:
        for s1 in reference_s1_ids:
            grouped[s1] = []

    for s1_id, cand_id, prob in scored_pairs:
        if prob >= threshold:
            if cand_id not in grouped[s1_id]:  # prevent duplicate IDs in row
                grouped[s1_id].append(cand_id)

    return dict(grouped)


def save_grouped_predictions(grouped: Dict[str, List[str]], output_path: str):
    """
    Save grouped predictions to TSV:
    source1_entity_id\tmatched_entity_ids
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    print(f"Writing {len(grouped):,} prediction rows to: {output_path}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("source1_entity_id\tmatched_entity_ids\n")
        for s1_id in sorted(grouped.keys()):
            matches_str = ",".join(grouped[s1_id])
            f.write(f"{s1_id}\t{matches_str}\n")

    print(f"Predictions successfully saved to {output_path}")


def run_prediction_pipeline(
    candidates_path: str,
    model_path: str,
    output_path: str,
    threshold: float = 0.80,
    reference_s1_path: Optional[str] = None,
):
    """
    Execute full inference pipeline.
    """
    print("=" * 60)
    print("STARTING INFERENCE & INTEGRATION PIPELINE")
    print("=" * 60)
    print(f"Candidates Path:    {candidates_path}")
    print(f"Model Path:         {model_path}")
    print(f"Output Path:        {output_path}")
    print(f"Matching Threshold: {threshold:.4f}")
    print("-" * 60)

    # Check dependencies before running
    if not os.path.isfile(candidates_path):
        print(f"[PENDING TEAMMATE 2]: Candidate file '{candidates_path}' does not exist yet.")
        print("Teammate 2 must first run candidate blocking (src/03_blocking.py).")
        return

    if not os.path.isfile(model_path):
        print(f"[PENDING TEAMMATE 3]: Model file '{model_path}' does not exist yet.")
        print("Teammate 3 must first train and save the model (src/05_train.py).")
        return

    # 1. Load candidates
    candidates = load_candidates(candidates_path)

    # 2. Load model
    model = load_trained_model(model_path)

    # 3. Features
    features = extract_features(candidates)

    # 4. Predict
    probabilities = predict_match_probabilities(model, features)

    # 5. Group & threshold
    ref_s1 = None
    if reference_s1_path and os.path.isfile(reference_s1_path):
        with open(reference_s1_path, "r", encoding="utf-8") as f:
            f.readline()
            ref_s1 = {line.split("\t")[0].strip() for line in f if line.strip()}

    # Integration placeholder for scored pairs
    scored_pairs = []  # will be populated once model & feature modules are linked
    grouped = group_predictions(scored_pairs, threshold=threshold, reference_s1_ids=ref_s1)

    # 6. Save
    save_grouped_predictions(grouped, output_path)
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Amazon ML Challenge - Inference & Integration Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--candidates",
        type=str,
        default="output/candidate_pairs.tsv",
        help="Path to candidate pairs TSV generated by 03_blocking.py",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="models/matching_model.joblib",
        help="Path to trained model artifact generated by 05_train.py",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="output/predictions.tsv",
        help="Path to save intermediate or final predictions TSV",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.80,
        help="Match classification probability threshold (default: 0.80)",
    )
    parser.add_argument(
        "--reference-s1",
        type=str,
        default=None,
        help="Path to reference source1 TSV to guarantee every S1 entity appears (even singletons)",
    )

    args = parser.parse_args()

    run_prediction_pipeline(
        candidates_path=args.candidates,
        model_path=args.model,
        output_path=args.output,
        threshold=args.threshold,
        reference_s1_path=args.reference_s1,
    )


if __name__ == "__main__":
    main()
